import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const BaseNeueBlack = localFont({
  src: "./fonts/BaseNeueBlack.tff",
  variable: "--font-BaseNeue",
  weight: "100 900",
});
const BasisLight = localFont({
  src: "./fonts/Basis-Light.woff",
  variable: "--font-Basis-Light",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AH Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${BasisLight.variable} ${BaseNeueBlack.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
