import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const tunnels = localFont({
  src: "./fonts/Tunnels.otf",
  variable: "--font-tunnels",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AH Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${tunnels.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
